# Generated by Django 5.0.1 on 2024-01-05 09:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='resources',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
