# Generated by Django 5.0.1 on 2024-01-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='date',
            field=models.DateField(),
        ),
    ]
