# Generated by Django 5.0.1 on 2024-02-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_target_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='notebook',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='NoteBook',
        ),
    ]
